# Generated by Django 3.1.7 on 2021-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExoplanetsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('discovery_year', models.IntegerField()),
                ('discovery_method', models.CharField(max_length=100)),
                ('light_years', models.IntegerField()),
                ('planet_mass', models.FloatField()),
                ('planet_radius', models.FloatField()),
                ('discovery_facility', models.CharField(max_length=100)),
            ],
        ),
    ]
